#!/bin/bash
vpython_path=../vpython-$(basename $(pwd))
if [ "$1" == "2" ]
then
  virtualenv $vpython_path
else
  python3.6 -m venv $vpython_path
fi
$vpython_path/bin/pip install --upgrade pip
$vpython_path/bin/pip install wheel flake8 ipython ipdb
